export type TriviaAPIResponse = {
  response_code: number;
  results: TriviaAPIResponseQuestion[];
};

export type TriviaAPIResponseQuestion = {
  type: string;
  difficulty: Difficulty;
  category: string;
  question: string;
  correct_answer: string;
  incorrect_answers: string[];
};

export type Question = {
  type: string;
  difficulty: Difficulty;
  category: string;
  question: string;
  correctAnswer: string;
  incorrectAnswers: string[];
};

export type Answer = {
  questionIndex: number;
  submitted: string | null;
  wasCorrect: boolean;
};

//NOTE - This is the result of a completed game -> send to backend as dto whenever user finishes a game
export type GameResult = {
  score: number;
  //datePlayed: string; // date is generated by spring -- no need to send it
  questions: Question[];
  answers: Answer[];
};

//NOTE - This is the logs of all previously completed games
// -> this should be fetched from backend later on (in context for now)
// we need to decide which games to fetch (e.g. last 5, all, last session etc.)
export type GameHistory = GameResult[];

export type Difficulty = "any" | "easy" | "medium" | "hard";

export const DIFFICULTIES: Difficulty[] = ["any", "easy", "medium", "hard"];

export type TriviaCategory = {
  id: number;
  name: string;
};

export const TRIVIA_CATEGORIES: TriviaCategory[] = [
  { id: 0, name: "Any Category" },
  { id: 27, name: "Animals" },
  { id: 25, name: "Art" },
  { id: 26, name: "Celebrities" },
  { id: 32, name: "Entertainment: Cartoon & Animations" },
  { id: 10, name: "Entertainment: Books" },
  { id: 29, name: "Entertainment: Comics" },
  { id: 16, name: "Entertainment: Board Games" },
  { id: 11, name: "Entertainment: Film" },
  { id: 31, name: "Entertainment: Japanese Anime & Manga" },
  { id: 12, name: "Entertainment: Music" },
  { id: 13, name: "Entertainment: Musicals & Theatres" },
  { id: 14, name: "Entertainment: Television" },
  { id: 15, name: "Entertainment: Video Games" },
  { id: 22, name: "Geography" },
  { id: 9, name: "General Knowledge" },
  { id: 23, name: "History" },
  { id: 20, name: "Mythology" },
  { id: 24, name: "Politics" },
  { id: 17, name: "Science & Nature" },
  { id: 18, name: "Science: Computers" },
  { id: 30, name: "Science: Gadgets" },
  { id: 19, name: "Science: Mathematics" },
  { id: 21, name: "Sports" },
  { id: 28, name: "Vehicles" },
] as const;

export type TriviaCategoryID = (typeof TRIVIA_CATEGORIES)[number]["id"];

export type GameState = "idle" | "playing" | "finished";
