//SECTION : type for fetched TriviaApi data

export type TriviaAPIResponse = {
  response_code: number;
  results: TriviaAPIResponseQuestion[];
};

export type TriviaAPIResponseQuestion = {
  type: string;
  difficulty: Difficulty;
  category: string;
  question: string;
  correct_answer: string;
  incorrect_answers: string[];
};

export type Difficulty = "any" | "easy" | "medium" | "hard";

export const DIFFICULTIES: Difficulty[] = ["any", "easy", "medium", "hard"];

export type TriviaCategory = {
  id: number;
  name: string;
};

export const TRIVIA_CATEGORIES: TriviaCategory[] = [
  { id: 0, name: "Any Category" },
  { id: 27, name: "Animals" },
  { id: 25, name: "Art" },
  { id: 26, name: "Celebrities" },
  { id: 32, name: "Cartoon & Animations" },
  { id: 10, name: "Books" },
  { id: 29, name: "Comics" },
  { id: 16, name: "Board Games" },
  { id: 11, name: "Film" },
  { id: 31, name: "Anime & Manga" },
  { id: 12, name: "Music" },
  { id: 13, name: "Musicals & Theatres" },
  { id: 14, name: "Television" },
  { id: 15, name: "Video Games" },
  { id: 22, name: "Geography" },
  { id: 9, name: "General Knowledge" },
  { id: 23, name: "History" },
  { id: 20, name: "Mythology" },
  { id: 24, name: "Politics" },
  { id: 17, name: "Science & Nature" },
  { id: 18, name: "Computers" },
  { id: 30, name: "Gadgets" },
  { id: 19, name: "Mathematics" },
  { id: 21, name: "Sports" },
  { id: 28, name: "Vehicles" },
] as const;

export type TriviaCategoryID = (typeof TRIVIA_CATEGORIES)[number]["id"];

//SECTION : types for game logic

export type GameState = "idle" | "playing" | "finished";

export type Question = {
  type: string;
  question: string;
  difficulty: Difficulty;
  category: string;
  correctAnswer: string;
  incorrectAnswers: string[];
};

export type Answer = {
  questionIndex: number;
  submittedAnswer: string | null;
  wasCorrect: boolean;
};

//SECTION : dto types for game data transferral

export type FinalGameDto = {
  //Game Entity
  savedScore: number;

  //GameAnswer Entity
  savedAnswers: Answer[];

  //Questions Entity -- questions that were wrong
  savedQuestions: Question[];
};

// // this should be sent first
// export type GameQuestionsDto = {
//   questions: Question[];
// };

// //NOTE - This is the result of a completed game -> send to backend as dto whenever user finishes a game
// export type GameResultDto = {
//   score: number;
//   //datePlayed: string; // date is generated by spring -- no need to send it
//   answers: Answer[];
// };

// // NOTE: A log from all previously completed games -> this should be fetched from backend later on (in context for now)
// // Biz logic: we need to decide WHICH and HOW MANY games to fetch (e.g. last 5, all, last session etc.)
// export type GameHistory = GameResultDto[]; // TODO - update to GameHistoryDto to be fetched from DB once saving is implemented

export type RetryQuestion = {
  id: number;
  wasCorrect: boolean;
  question: Question;
};

export type RetryQuestionResponse = {
  id: number;
  archived: boolean;
};

export type RetryCounts = {
  easy: number;
  medium: number;
  hard: number;
};
